import Head from "next/head";
import React from "react";

const MetaComponent = () => {
  return (
    <>
      <Head>
        <title>School of commerce technology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default MetaComponent;
